# Generated by Django 2.2 on 2019-06-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioparametros',
            name='id',
        ),
        migrations.AddField(
            model_name='usuarioparametros',
            name='Apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuarioparametros',
            name='Nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarioparametros',
            name='documento',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
