# Generated by Django 2.2 on 2019-06-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'verbose_name': 'Estado Civil', 'verbose_name_plural': 'Tipos de Estados Civiles'},
        ),
    ]
