# Generated by Django 2.2 on 2019-06-27 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190626_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioparametros',
            name='documento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarioparametros',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
