# Generated by Django 2.1.8 on 2019-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190627_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioparametros',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
