# Generated by Django 2.2.2 on 2019-06-11 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombMetPago', models.CharField(default='', max_length=45, verbose_name='Nombre método de pago')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
            },
        ),
        migrations.CreateModel(
            name='DetalleMet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('IdMetodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccion.MetodoPago', verbose_name='Método de pago')),
            ],
            options={
                'verbose_name': 'Detalle método',
                'verbose_name_plural': 'Detalles métodos',
            },
        ),
    ]
