# Generated by Django 2.2 on 2019-06-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Detalle método',
                'verbose_name_plural': 'Detalles métodos',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombMetPago', models.CharField(default='', max_length=45, verbose_name='Nombre método de pago')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.FloatField(verbose_name='Total de la transaccion')),
                ('DetaMet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccion.DetalleMet', verbose_name='Detalle del Metodo')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleTra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('IdTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccion.Transaccion', verbose_name='Transaccion')),
                ('Usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Detalle Transaccion',
                'verbose_name_plural': 'Detalles Transacciones',
            },
        ),
        migrations.AddField(
            model_name='detallemet',
            name='IdMetodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaccion.MetodoPago', verbose_name='Método de pago'),
        ),
    ]
