# Generated by Django 2.2 on 2019-06-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nomnbre Tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, verbose_name='token')),
                ('alias', models.CharField(max_length=50, verbose_name='Nombre Alias')),
                ('contaseña', models.CharField(default='', max_length=50, verbose_name='Contraseña')),
                ('correo', models.CharField(default='@', max_length=50, verbose_name='Correo Electronico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el : ')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado el : ')),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='DatosUsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('documento', models.CharField(max_length=50, verbose_name='No. Documento')),
                ('telefono', models.CharField(default='0', max_length=50, verbose_name='No. Telefono')),
                ('edad', models.CharField(default='0', max_length=50, verbose_name='Edad')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el : ')),
                ('update_ad', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado el : ')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario', verbose_name='Identificacion del Usuario')),
            ],
        ),
    ]
